language: objective-c
osx_image: xcode12.5

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilSDKRatchet.xcodeproj
    - IOS_SDK=iphonesimulator14.5
    - MACOS_SDK=macosx11.3
    - TVOS_SDK=appletvsimulator14.5
    - WATCHOS_SDK=watchsimulator7.4
    - FRAMEWORK_NAME=VirgilSDKRatchet
    - REPO=VirgilSecurity/virgil-ratchet-x
    - REPO_PATH=https://github.com/VirgilSecurity/virgil-ratchet-x.git

  matrix:
    - DESTINATION=""                                           PREFIX=""         SDK=""              BUILD="0"  PUBLISH_CARTHAGE="YES"  CARTHAGE_PLATFORM="Mac"         PUBLISH_POD="YES"  SWIFT_LINT="YES"  PUBLISH_DOCS="YES"
    - DESTINATION="OS=14.5,name=iPhone 8"                      PREFIX="iOS"      SDK="$IOS_SDK"      BUILD="2"  PUBLISH_CARTHAGE="NO"   CARTHAGE_PLATFORM="iOS"      PUBLISH_POD="NO"   SWIFT_LINT="NO"   PUBLISH_DOCS="NO"
    - DESTINATION="arch=x86_64"                                PREFIX="macOS"    SDK="$MACOS_SDK"    BUILD="2"  PUBLISH_CARTHAGE="NO"   CARTHAGE_PLATFORM="Mac"      PUBLISH_POD="NO"   SWIFT_LINT="NO"   PUBLISH_DOCS="NO"
    - DESTINATION="OS=14.5,name=Apple TV"                      PREFIX="tvOS"     SDK="$TVOS_SDK"     BUILD="2"  PUBLISH_CARTHAGE="NO"   CARTHAGE_PLATFORM="tvOS"     PUBLISH_POD="NO"   SWIFT_LINT="NO"   PUBLISH_DOCS="NO"
    - DESTINATION="OS=7.4,name=Apple Watch Series 6 - 40mm"    PREFIX="watchOS"  SDK="$WATCHOS_SDK"  BUILD="1"  PUBLISH_CARTHAGE="NO"   CARTHAGE_PLATFORM="watchOS"  PUBLISH_POD="NO"   SWIFT_LINT="NO"   PUBLISH_DOCS="NO"

before_install:
  - set -e
  - set -o pipefail

script:
  - openssl aes-256-cbc -K $encrypted_c69be59365f7_key -iv $encrypted_c69be59365f7_iv -in config.tar.enc -out config.tar -d
  - tar xvf config.tar

  - |
    if [ -n "$TRAVIS_TAG" ]; then
      cp TestConfig_prod.plist Tests/Data/TestConfig.plist
    else
      cp TestConfig_stg.plist Tests/Data/TestConfig.plist
    fi

  - carthage version
  - carthage bootstrap --use-xcframeworks --platform $CARTHAGE_PLATFORM

  - |
    if [ $SWIFT_LINT == "YES" ]; then
      brew outdated swiftlint || brew upgrade swiftlint
      swiftlint
    fi

  - PROJ="VirgilSDKRatchet"
  - SCHEME="${PROJ} ${PREFIX}"

  - |
    if [ $BUILD == "2" ]; then
        # Build Framework
        xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean build-for-testing | xcpretty;
        # Run Tests
        xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test-without-building | xcpretty;
      elif [ $BUILD == "1" ]; then
        # Build Framework
        xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;
      fi

  # Build with carthage
  - if [[ $PUBLISH_CARTHAGE == "YES" && $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
        ./CI/publish-carthage.sh;
    fi
  
  # Publish docs
  - if [[ $PUBLISH_DOCS = "YES" && $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
      ./CI/publish-docs.sh;
    fi

before_deploy:
  - carthage archive

deploy:
  - provider: releases
    api_key: $GITHUB_ACCESS_TOKEN
    file:
      - "$FRAMEWORK_NAME.xcframework.zip"
    skip_cleanup: true
    on:
      repo: $REPO
      tags: true
      condition: $PUBLISH_CARTHAGE = "YES"

  - provider: script
    script: bash CI/publish-cocoapods.sh
    on:
      repo: $REPO
      tags: true
      condition: $PUBLISH_POD == "YES" && $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+

  # Upload docs to gh-pages
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_ACCESS_TOKEN
    local_dir: "docs"
    on:
      repo: $REPO
      tags: true
      condition: $PUBLISH_DOCS == "YES" && $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+

